# Generated by Django 2.2.2 on 2019-07-20 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actuators',
            },
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('api', models.FileField(blank=True, null=True, upload_to='api')),
            ],
            options={
                'verbose_name_plural': 'API',
            },
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('api', models.FileField(blank=True, null=True, upload_to='mailbox')),
            ],
            options={
                'verbose_name_plural': 'MailBox',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('name', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='ServiceRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Service Registry',
            },
        ),
    ]
