# Generated by Django 2.2.3 on 2019-08-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
