# Generated by Django 2.2.3 on 2019-08-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_api_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='fields',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
