# Generated by Django 2.2.3 on 2019-08-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190802_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='fields',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
