# Generated by Django 2.2.3 on 2019-08-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190802_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='connection',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
