# Generated by Django 2.2.3 on 2019-08-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_api_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('fields', models.TextField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Interactive',
            },
        ),
    ]
